#!/usr/bin/env python3

import os
import sys
import pwd
import stat
import subprocess as subp
import shutil as sh

PRIVILEGED_FILES = [
            ("tile_active_window", "/usr/bin/tile_active_window", 0o755),
        ]

FILES = [
            ("xbindkeys.rc", os.path.join(os.path.expanduser("~"), ".xbindkeysrc"), 0o644),
        ]

def log(*args, **kwargs):
    #return print(*args, **kwargs)
    pass

def copyfile(srcPath, destPath):
    print("Copying {} => {}".format(srcPath, destPath))
    sh.copyfile(srcPath, destPath)

def setPermissions(path, perm):
    print("Setting permissions for {} to {:o}".format(path, perm))
    os.chmod(path, perm)

#Throws OSError exception (it will be thrown when the process is not allowed
#to switch its effective UID or GID):
def drop_privileges():
    if os.getuid() != 0:
        # We're not root so, like, whatever dude
        return

    # Get the uid/gid from the name
    user_name = os.getenv("SUDO_USER")
    pwnam = pwd.getpwnam(user_name)

    # Remove group privileges
    os.setgroups([])

    # Try setting the new uid/gid
    os.setgid(pwnam.pw_gid)
    os.setuid(pwnam.pw_uid)

    # Ensure a reasonable umask
    old_umask = os.umask(0o22)

def install_files(srcDir, files):
    #copy files and set permissions
    for fileName, destPath, perm in files:
        srcPath = os.path.join(srcDir, fileName)
        copyfile(srcPath, destPath)
        setPermissions(destPath, perm)

def run(args):
    log("run({})".format(args))
    retVal = subp.check_output(args).decode('utf_8', 'replace').strip()
    if retVal:
        log(retVal)
    return retVal

def reloadXbindkeysConfig():
    try:
        print("Terminating all xbindkeys processes")
        run(['killall', 'xbindkeys'])
    except:
        pass
    finally:
        print("Trying to start the xbindkeys service.")
        run(['xbindkeys'])

def main(progPath, args):
    baseDir = os.path.dirname(progPath)
    install_files(baseDir, PRIVILEGED_FILES)
    drop_privileges()
    install_files(baseDir, FILES)
    reloadXbindkeysConfig()

if __name__ == '__main__':
    try:
        main(sys.argv[0], sys.argv[1:])
    except Exception as e:
        print(e)
    except:
        print("ERROR: Unknown error.")